### ISSUE TITLE
How to handle conflicting primary sources

### ISSUE THREAD

**Issue by Flyingmana** [FriendsOfPHP/security-advisories#108]
Hi, me again,

so now we have directly a case, where the first primary source describes a bigger affected version area then a review from another source I would also call as primary.

https://github.com/Cotya/magento-security-advisories/pull/1

So I think another optional list for linking to reviews would be wise, while I would not change the affected range yet, if not at least two reviews come to the same result.

Do you think this makes sense?

**Comment by fabpot** [comment]
I'm not sure to understand what is not covered in the referenced PR. Sorry I'm not familiar with Magento, so I would need a dump of something you would want to achieve and that is not yet possible.

**Comment by Flyingmana** [comment]
Thats not really magento specific, just a special case.

Timeline:  
first source makes security flaw public, describes the version range with "prior to version 1.3.10" which I think would mean the same as "<1.3.10"  
another source reviews this for an own analyses later, and comes to the conclusion, the affected versions are only ">=1.3.8,<1.3.10"

So they conflict in what they say, and I dont know what the best way to handle this would be.

**Comment by reiz** [comment]
I would say in that case somebody has to try to reproduce the sec. flaw for the affected versions. If not possible I would recommend to take the wider range to be sure.

**Comment by michaelcullum** [comment]
Follow what the vendor says? If in doubt just ask the vendor or look at what they've announced?

Unless magneto are saying two things? But that repository you linked to even says this in their readme.md:
> Magento related Security Advisories Database
>The Magento related Security Advisories Database references known security vulnerabilities in various Magento Versions and 3rd Party Modules. This database must not serve as the primary source of information for security issues, it is not authoritative for any referenced software, but it allows to centralize information for convenience and easy consumption.
>
>This project is completely community driven.
