### ISSUE TITLE
How are branches related to versions in composer?

### ISSUE THREAD

**Issue by reiz** [FriendsOfPHP/security-advisories#114]
How are the branch names related to the version strings in composer? [Here](https://github.com/FriendsOfPHP/security-advisories/blob/master/doctrine/mongodb-odm-bundle/2015-08-31.yaml#L5) for example the branch 3.0 has a versions array with `[>=2.0.0,<3.0.1]`. I thought the versions array has to fit to the branch name. If so the array should be `[>=3.0.0,<3.0.1]`. Right? 

Which versions on Packagist/Composer are now affected from this security vulnerability? 3.0.0 only? Or everything bigger 2.0.0 up to and including 3.0.0?

**Comment by stof** [comment]
branch names are actually not used for anything except authoring AFAIK. The constraint is what defines the affected versions

The final constraint matched by the advisory is built by joining the constraints of each branches using OR (while the different values in the array of constraints of a branch are joined with a AND, which is very readable as the comma separating array elements in YAML is also a way to write AND in composer constraints).

**Comment by reiz** [comment]
OK. Thanks for your answer. That's how it is implemented in VersionEye.
