### ISSUE TITLE
Implement auto-merging of advisories by a bot

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/security-advisories#218]
Currently, merging new advisories in the repo involves manual work from @fabpot. This could delay merging if he is not available (he can take vacations for instance).

I suggest implementing a system when multiple people can approve advisories, and then have a bot merging them automatically if the PR is approved and CI is green.

Note that this also implies that https://security.sensiolabs.org/ must be updated automatically with the new advisory. I have no idea how the update is handled currently.

What do you think @fabpot ?

**Comment by fabpot** [comment]
Merging is manual but website updates are automatic.

Doing the merge automatically like for Symfony recipes is a good idea. I will work on this later this year. For now, merging manually is quite easy and can be done from my phone, so I'm always very fast (less than a few hours recently).

**Comment by stof** [comment]
yeah, I noticed that the delay was not that bad already, so this is indeed not a huge priority.

**Comment by gggeek** [comment]
On a side note: what about a bot/cronjob that scans the internet to feed notices of vulns to add?

We could scan, say, cvedetails.com, looks for the word 'php' (plus well known php apps/framework names). if found, look up a match on packagist. If a match is found, we could look at composer.json of the developers and send them a mail asking to add the info to this db. Or maybe post an issue in their github tracker...

**Comment by stof** [comment]
@gggeek I suggest opening a dedicated issue to discuss this, as it is a totally different topic.

**Comment by fabpot** [comment]
Closing as the volume of PRs is low and all PRs are merged quite fast anyway already.
