### ISSUE TITLE
Advistories typo

### ISSUE THREAD

**Issue by PhilETaylor** [FriendsOfPHP/security-advisories#223]
I know this is not the right place for this but I cannot find any repo to report this to and I think you guys might be one and the same or at least know the right people to tell :) 

The word "Advistories" is spelled wrong in the dropdown on security.sensiolabs.org: 

![screen shot 2017-09-02 at 16 51 06](https://user-images.githubusercontent.com/400092/29996891-f0e89406-8ffe-11e7-963d-963ff3d14bfa.png)

// @fabpot

**Comment by PhilETaylor** [comment]
Also the "Get support from SensioLabs" link in the footer goes to https://sensiolabs.com/support which redirects to https://sensiolabs.com/en/enterprise-subscription/symfony-support.html which is a 404 error page :)

**Comment by fabpot** [comment]
fixed now, thanks for the report.

**Comment by PhilETaylor** [comment]
Awesome. You're welcome!
