### ISSUE TITLE
typo in phpxmlrpc/extras/2017-10-29.yaml ?

### ISSUE THREAD

**Issue by b4stet** [FriendsOfPHP/security-advisories#245]
Hello,

in https://github.com/FriendsOfPHP/security-advisories/blob/master/phpxmlrpc/extras/2017-10-29.yaml#L7, there might be a typo in 'versions' (line 6): '[<0.6.1]' instead of '[<6.0.1]' ?

bests

**Comment by xabbuh** [comment]
It seems so. Would you like to submit a pull request?

**Comment by b4stet** [comment]
done in #246
