### ISSUE TITLE
[VULN] FOSUserBundle change host location

### ISSUE THREAD

**Issue by grelu** [FriendsOfPHP/security-advisories#294]
I opened an issue here https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2787

Can you reproduce that ?
Thanks for reply.

**Comment by fabpot** [comment]
I'm closing here as this repository is only used to reference security issues when releases have been published.

**Comment by grelu** [comment]
Ok, I'm sorry. But it's Titouan Galopin (Symfony Support) who told me to do that.
