### ISSUE TITLE
Timezone of time entries?

### ISSUE THREAD

**Issue by lxp** [FriendsOfPHP/security-advisories#309]
The contribution guidelines mention that `time` entries should be as accurate as possible, but which timezone is not mentioned.
Should it be the native timezone of the (merge) commit or UTC?

**Comment by cebe** [comment]
> native timezone of the (merge) commit

this is quite vague as it is not clear which timezone that actually is unless it is specified.
The current description does not allow adding a timezone so I assume it should be UTC.

**Comment by lxp** [comment]
Thanks for clarification!
I suspected that it would be UTC, but as it was not mentioned explicitly I thought it should be documented.
