### ISSUE TITLE
Issue with security info for root package ezsystems/ezplatform

### ISSUE THREAD

**Issue by andrerom** [FriendsOfPHP/security-advisories#355]
After addtion of https://github.com/FriendsOfPHP/security-advisories/blob/master/ezsystems/ezplatform/2018-11-21-1.yaml by @glye, many users reports being unable to install latests or update to versions due to our usage of `roave/security-advisories`. In these cases composer is unable to determine version of root package so it gives it a version of `v1.0.0` and composer stops with package conflict.

We have changed `roave/security-advisories` in favour of `sensiolabs/security-checker` in https://github.com/ezsystems/ezplatform/commit/4e94c9552d28961e4251252b1cccd453ac96924f, however that won't help users already with a install. And afaik `sensiolabs/security-checker` does not check root package anyway.

As `roave/security-advisories` auto generates their rules from the source here and thus won't accept changes, I'm wondering if we can add a syntex match for 1.0.x and say =<1.0.0 is valid to avoid it, with some inline comment here about why. Alternative is that we remove it for this package.

Any suggestions/conventions?

**Comment by Ocramius** [comment]
You can say `>=1.0.0`?

**Comment by Ocramius** [comment]
Can you make a set of steps to reproduce the issue?

**Comment by xabbuh** [comment]
Does the entry make any sense at all? I mean will users ever add `ezsystems/ezplatform` as a dependency in their project? IIUC this package is just a template for bootstrapping new applications, isn't it (similar to what `symfony/framework-standard-edition` used to be for Symfony in the past)?

**Comment by glye** [comment]
It looks like the most sensible and easiest solution is to remove the ezplatform entries from security-advisories. I'll do a PR.

**Comment by Ocramius** [comment]
This can only be done if `ezsystems/ezplatform` is not the actual source of the security issue.

**Comment by andrerom** [comment]
Well we could argue `symfony/symfony-standard` is the source, as it's upstream of the repo in question here. But that highly depends on how the fix is done to the issue.

Or we can argue that root repos should not be listed in `roave/security-advisories`.

**Comment by Ocramius** [comment]
> root/project repos should not be listed

If they contain the offending code, they should be listed.

**Comment by stof** [comment]
Well, a bootstrapping template does not really make sense for the advisory repo. A project will never depend on it.

**Comment by andrerom** [comment]
> If they contain the offending code, they should be listed.

There is actually no offending code in this security advisor, it's a enhancement and not strictly a bug:
https://github.com/ezsystems/ezplatform/commit/9a0c52dc4535e4b3ce379f80222dc53f705a2cfd#diff-64a0fd926147fcc158821dcb6f1b4d11

So that's an argument for not listing it here. But ultimately like @stof I also don't think template repos should be listed here in the first place.

**Comment by Ocramius** [comment]
> it's a enhancement and not strictly a bug

Really looks like the exact code to fix a security issue, to me, but that's up to maintainers of that repo to decide, I suppose.

**Comment by glye** [comment]
If there is no way to set & determine the version of the root package (and it will indeed not be depended on by others), then it doesn't make sense to keep it I think, even if it does fix a security issue. Causes more trouble than it fixes. https://github.com/FriendsOfPHP/security-advisories/pull/356
