### ISSUE TITLE
Advisories for Drupal contrib

### ISSUE THREAD

**Issue by eiriksm** [FriendsOfPHP/security-advisories#366]
Hello!

Just wondered if having advisories for Drupal contributed modules in here would be possible/wanted?

They generally do not have a CVE, and of course they would have to be maintained by someone. My thinking was to create a script that parses the advisories available, and programatically create PRs for the ones that were missing. This would help to keep it up to date as well, I could run the script periodically.

Thanks for this package btw, it is very useful!

**Comment by eiriksm** [comment]
Link to Drupal contrib advisories, for context: https://www.drupal.org/security/contrib

**Comment by fabpot** [comment]
Issues without CVEs are ok.
Having Durpal contributed module issues is ok as well.
Having an automated process works for me (Typo3 has a script to automate the process as well -- https://github.com/TYPO3/darth/commit/4524eec445d4a785127232fea0324e8d4f5cf7f2), but please, don't create hundreds of PRs. One with everything is enough and then one PR from time to time to update things.

**Comment by eiriksm** [comment]
Good point, will do so!

**Comment by hugovk** [comment]
@eiriksm Will you update the advisories here for https://www.drupal.org/SA-CORE-2019-003 and related modules? Thanks!

https://www.drupal.org/security

**Comment by eiriksm** [comment]
No problem, created one for core now.

The contribs, however, is what this issue is talking about, and will probably be part of one big initial PR in hopefully not too long (when I get time to finish it).

**Comment by eiriksm** [comment]
OK, so I prepared a huge dump of advisories for Drupal contrib.

However, they fail validation because of the following (example):

The yaml file looks like this:

```yml
link: 'https://www.drupal.org/sa-contrib-2017-091'
title: 'Configuration Update Manager - Moderately critical - Cross Site Request Forgery (CSRF) - SA-CONTRIB-2017-091'
branches:
    8.x-1.x: { time: '2019-02-21 22:21:04', versions: ['>=1.0.0', '<1.5.0'] }
reference: 'composer://drupal/config_update'

```

```
| drupal/config_update/sa-contrib-2017-091.yaml                | Invalid composer package (not found in repository https://packagist.org) |
|                                                              | Invalid branch name "8.x-1.x".                                           |
```

Now, I went through the code, and discovered the undocumented property "composer-repository" one could set in the yaml file. So if I change that to point to packages.drupal.org, like we use, that seems to take care of that. I will open a README PR if this is OK and supported.

Now for the other part. As you can see from for example here: http://cgit.drupalcode.org/config_update the branch is actually called 8.x-1.x. And this fails.

Since does not follow semver for contrib, the closest correct way (in this example) would be to have it like this (or similar):

```yml
link: 'https://www.drupal.org/sa-contrib-2017-091'
title: 'Configuration Update Manager - Moderately critical - Cross Site Request Forgery (CSRF) - SA-CONTRIB-2017-091'
branches:
    1.0.x: { time: '2019-02-21 22:21:04', versions: ['>=1.0.0', '<1.5.0'] }
    1.1.x: { time: '2019-02-21 22:21:04', versions: ['>=1.0.0', '<1.5.0'] }
    1.2.x: { time: '2019-02-21 22:21:04', versions: ['>=1.0.0', '<1.5.0'] }
    1.3.x: { time: '2019-02-21 22:21:04', versions: ['>=1.0.0', '<1.5.0'] }
    1.4.x: { time: '2019-02-21 22:21:04', versions: ['>=1.0.0', '<1.5.0'] }
    1.5.x: { time: '2019-02-21 22:21:04', versions: ['>=1.0.0', '<1.5.0'] }
composer-repository: 'https://packages.drupal.org/8'
reference: 'composer://drupal/config_update'
``` 

This makes it validate, and all is good. Is this the way to approach it for now?

**Comment by stof** [comment]
for tagged releases, what is important is the version range, not the branch name anyway (and so you don't need to put all branches with the full range in your example, especially if older branches don't contain the fix at all)

**Comment by eiriksm** [comment]
OK, fair enough. But the problem here is that I can't even put the real branch name in there. So in this example, the branch is called 8.x-1.x and it is the only branch. But I can't put that as branch, since that does not validate. Should I put one branch in there, and call it 1.5.x then? Or call it 1.x or 8.x?

**Comment by stof** [comment]
I suggest naming `1.5.x`, as that matches the version range

**Comment by stof** [comment]
this got reverted, because the drupal-contrib packages broke the usage of this advisory DB due to the fact that the same `package name + version` can appear in both the Drupal 7 and Drupal 8 repositories, while they represent the same package release as far as composer and its tooling are used.

**Comment by eiriksm** [comment]
Makes sense. Just another reason we should try to move to semantic versioning in Drupal land ;)
