### ISSUE TITLE
Is there a way to restrict installing abandon libraries because of security issue?

### ISSUE THREAD

**Issue by vijaycs85** [FriendsOfPHP/security-advisories#372]
We have a few packages in Drupal that are unsupported because of security issues(e.g. https://www.drupal.org/sa-contrib-2019-006). Is there a way to not allow to install (any version) them?

**Comment by colinodell** [comment]
I think this might be outside the scope of this project.

Composer offers [a way to mark projects as `abandoned`](https://getcomposer.org/doc/04-schema.md#abandoned) - it's up to Drupal to provide this information in their Composer repositories. Assuming they do this (they should, but I don't actually know if they do) then you should be seeing warnings in Composer's output similar to this:

![](https://i.stack.imgur.com/HCuIx.png)

That won't prevent installation though - you'll probably need to find or create a plugin to help automate that for you.

**Comment by vijaycs85** [comment]
Thanks @colinodell I will check.

**Comment by legoktm** [comment]
See also #319 for a bit of discussion on what to do when there's a known security issue with no fixed version.
