### ISSUE TITLE
Drupal security release

### ISSUE THREAD

**Issue by mikkeschiren** [FriendsOfPHP/security-advisories#389]
Drupal core - Moderately critical - Multiple Vulnerabilities - SA-CORE-2019-005 & Drupal core - Moderately critical - Cross Site Scripting - SA-CORE-2019-006

https://www.drupal.org/sa-core-2019-005
https://www.drupal.org/sa-core-2019-006

Pull request: https://github.com/FriendsOfPHP/security-advisories/pull/388

**Comment by stof** [comment]
@mikkeschiren no need to open an issue for that. The PR is enough.
