### ISSUE TITLE
TYPO3 extension advisories

### ISSUE THREAD

**Issue by smichaelsen** [FriendsOfPHP/security-advisories#401]
https://github.com/smichaelsen/no-insecure-typo3-extensions

I've built an equivalent of roave/security-advisories for TYPO3 extensions, which is automatically updated based on the extension ratings of the TYPO3 security team.

Would it be of interest to incorporate that list into this project? Maybe my script could automatically open a PR when the TYPO3 security team publishes new advisories on extensions.

**Comment by fabpot** [comment]
Thanks for the information. This repository is only about the security vulns DB and I don't want to add any opinionated features.

**Comment by smichaelsen** [comment]
The source (TYPO3 security team) is the same as for the TYPO3 core advisories that you include in this project, so I'm not sure I understand the "opinionated" thing. But thanks anyway for the quick reply.

**Comment by fabpot** [comment]
This repository is only about a database of vulnerabilities.

And I personally don't like the way roave avoids installing unsecure packages.

**Comment by Ocramius** [comment]
> And I personally don't like the way roave avoids installing unsecure packages.

Well, it's a zero-dependencies, zero-sources approach, with the downside that it has to act during `composer update`. For me, that's already a big win, from an engineering PoV.

That said, I don't expect advertising from the upstream repository: this is just a database, and that's OK :+1:
