### ISSUE TITLE
Flag unsupported versions

### ISSUE THREAD

**Issue by Rudloff** [FriendsOfPHP/security-advisories#504]
Is there a way to flag unsupported versions that explicitly don't receive any security fix anymore?
These should not be used even if there is no known vulnerability.

It would not apply to every project but big projects like Drupal announce official dates for the end of security coverage for each branch.

It would also help in cases like https://github.com/FriendsOfPHP/security-advisories/pull/502#discussion_r527123270 where we don't know when a vulnerability was introduced but we know older versions should not be used anyway.

**Comment by fabpot** [comment]
No, there is no such flag. And that's probably out of the scope of this repository (as not related to security per se).
