### ISSUE TITLE
propel: 2.0.0-alpha11

### ISSUE THREAD

**Issue by DawoudIO** [FriendsOfPHP/security-advisories#511]
Based on this https://github.com/propelorm/Propel2/issues/1675

the following does not apply to 1propel/propel": "2.0.0-alpha11`

 I'm still getting the error 
https://github.com/ChurchCRM/CRM/runs/1471875270?check_suite_focus=true

Other files to note
https://github.com/FriendsOfPHP/security-advisories/blob/master/propel/propel/2018-02-14.yaml
https://github.com/ChurchCRM/CRM/blob/master/src/composer.json

**Comment by thirdender** [comment]
It looks to me like the security-advisory lists the correct versions, but the tool you're using doesn't understand the "-alphaX" portion of the version string. I think an issue needs to be raised for the [symfony/cli](https://github.com/symfony/cli/issues/new) repo to address the tool that is parsing the version strings.

**Comment by fabpot** [comment]
We should not have entries for alpha versions IMHO.

**Comment by Ocramius** [comment]
Propel alpha is sadly very widespreadly used, so it's probably stable software that is not declared as such.

IMO valid to notify users that they are running something harmful.

**Comment by fabpot** [comment]
The whole code is now Open-Source at https://github.com/fabpot/local-php-security-checker (server + client code, so no more API calls). Feel free to submit a PR there to fix this bug.

**Comment by dereuromark** [comment]
The false positive is still present though it seems - the source of the problem seems still to be that the tool cannot properly see the order of non trivial release versions, e.g. alpha, beta, RC:

    2.0.0-alpha1 < 2.0.0-alpha11 < 2.0.0-alpha2

the tool thinks - which is incorrect.

**Comment by thirdender** [comment]
I think I'm in agreement with @fabpot that there should not be any alpha/beta/rc identifiers. The SemVer spec does not consider these pre-release tags when comparing versions. See https://interrupt.memfault.com/blog/release-versioning for a good write-up of SemVer. Ideally the Propel2 library should increment the patch version number and not the "alpha" number.

**Comment by stof** [comment]
@thirdender as this targets composer packages, it should support things that composer accepts.

**Comment by stof** [comment]
semver definitely considers pre-release tags. But the official semver spec requires a `.` between the prerelease identifier (`alpha`) and the prerelease version (so `2.0.0-alpha.11`).

**Comment by thirdender** [comment]
Hmm, the article and SemVer library I'm using are both wrong then. Thanks for digging that up, looks like I have some more research to do.

**Comment by Ocramius** [comment]
Related: https://github.com/Roave/SecurityAdvisoriesBuilder/pull/98 - @slash3b worked quite a lot to add support for patch version modifiers, should you need inspiration.

**Comment by stof** [comment]
I opened https://github.com/fabpot/local-php-security-checker/issues/9 on the checker project itself to track this, in case someone wants to contribute.
