### ISSUE TITLE
Provide an RSS feed

### ISSUE THREAD

**Issue by DavidPrevot** [FriendsOfPHP/security-advisories#53]
It would be nice if the [database](https://security.sensiolabs.org/database) were also available via an RSS/Atom feed.

**Comment by fabpot** [comment]
Done.

https://security.sensiolabs.org/database.rss for all vulnerabilities
https://security.sensiolabs.org/database.rss?package=symfony/symfony for a specific package.

**Comment by DavidPrevot** [comment]
Hi,

> https://security.sensiolabs.org/database.rss for all vulnerabilities
> https://security.sensiolabs.org/database.rss?package=symfony/symfony for a
> specific package.

Nice! Thanks a lot!

**Comment by pborreli** [comment]
>```<guid isPermaLink="true">73e72916e70534291453c2d13602e25dce9e9914</guid>```

`isPermaLink="true"` should be false and unique (16268988ddd920720032407178b97534427420ac is in double)

**Comment by micayael** [comment]
Nice! :+1: 

The package symfony/symfony includes symfony/*?
