### ISSUE TITLE
Work with Github to fix their Advisory Database importer?

### ISSUE THREAD

**Issue by chillu** [FriendsOfPHP/security-advisories#537]
Github used to import FriendsOfPHP vulnerabilities until at some point last year - see an [archived version](https://web.archive.org/web/20200704064916/https://docs.github.com/en/github/managing-security-vulnerabilities/browsing-security-vulnerabilities-in-the-github-advisory-database) of their [docs](https://docs.github.com/en/github/managing-security-vulnerabilities/browsing-security-vulnerabilities-in-the-github-advisory-database)). I've been contact with Github support twice to flag that their importer seems to be broken - it's only importing a [fraction](https://github.com/advisories?query=silverstripe) of the [advisories](https://github.com/FriendsOfPHP/security-advisories/tree/master/silverstripe) we (`silverstripe`) publish to FriendsOfPHP.

I might have been the cause for Github removing claims about importing FriendsOfPHP, in my view security related features and information should provide high quality data - and showing the occasional vulnerability alert for our ecosystem meant that devs will get a false sense of security through the feature. The lack of alerts on their Github repo does *not* mean they run a secure installation of our dependencies.

Have you contacted Github about this in any way? It's such a useful feature to the PHP community, I'm keen to get some momentum for them to reinstate their importer.

**Comment by stof** [comment]
Looks like they stopped importing this database at all.

For the silverstripe case, I would say that the ones appearing on github are the ones that have a CVE assigned, because they are imported by Github from the CVE database.

**Comment by chillu** [comment]
Thanks for looking into this! We've got CVEs (through Mitre) for 57 vulns, yet Github lists only 7. See [NVD for "silverstripe" vendor](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Asilverstripe). So even for the CVE import (which they appear to be doing through NVD) I'm not quite sure how that importer functions.

Symfony appears to have the same issue: [16 advisories in Github](https://github.com/advisories?query=symfony), and well over [30 advisories in symfony.com](https://symfony.com/blog/category/security-advisories).

Maybe you could try contacting them? Github Advisories are such a useful feature for the PHP community if they can make them accurate. I've tried my luck already, might carry more weight if it comes from another PHP project and the maintainer of the source they've claimed to import before?

**Comment by fabpot** [comment]
Unfortunately, we don't have the resources nor the time to talk to consumers of this database. Let's close here as I won't be able to do anything here. Of course, I would be more than happy if more projects would try to fix the issue with Github.
