### ISSUE TITLE
Typosquatting Malware  symfont/process

### ISSUE THREAD

**Issue by wjonkerhulst** [FriendsOfPHP/security-advisories#587]
Best,

I would like to add the Typosquatting Malware symfont/process (https://www.kernelmode.blog/typosquatting-malware-found-in-composer-repository/) to this project but do not know how to do this because the malware itself has no corresponding cve.

Is it possible to add a vulnerability without a cve to this project?

Kind regards,
Wilfried

**Comment by fabpot** [comment]
Yes, no need for a cve

**Comment by derrabus** [comment]
Can this package be removed from Packagist?

@naderman @Seldaek

**Comment by Seldaek** [comment]
It's gone now
