### ISSUE TITLE
EOL components

### ISSUE THREAD

**Issue by tvlooy** [FriendsOfPHP/security-advisories#65]
When components are EOL, especially old Symfony versions, do these get a security warning or something? I just checked a 2.2 project and it doesn't mention something like "this version is EOL and will not get security updates".

**Comment by Ocramius** [comment]
@tvlooy EOL = nobody updates it. That includes adding notices.

**Comment by stof** [comment]
An EOLed component does not mean it is insecure. So there is no reason to display a warning when using it.
The way things are done currently is that new advisories mention all affected versions, even EOLed ones. But for EOLed versions, there won't be any fixed version, so the only way to fix this warning would be to upgrade to a maintained version.

**Comment by tvlooy** [comment]
an EOL component could mean it is not audited and checked against CVE's. But, I see idd that the advisories are for all versions, even EOL ones. Great!
