### ISSUE TITLE
Missing api-platform CVE

### ISSUE THREAD

**Issue by rmikalkenas** [FriendsOfPHP/security-advisories#674]
Missing https://github.com/advisories/GHSA-vr2x-7687-h6qv
Is this repository still active and is it safe to use symfony's security:checker cli?

**Comment by derrabus** [comment]
> Missing [GHSA-vr2x-7687-h6qv](https://github.com/advisories/GHSA-vr2x-7687-h6qv)

Please send a PR.

> Is this repository still active

Yes.

> and is it safe to use symfony's security:checker cli?

Sure, but there's also `composer audit` now which uses this repository as one of its sources.
